robotName: Nymph
prefix: 指挥官阁下，Nymph为你查询到以下信息：
host: http://nymph.rbq.life:3000/
dev:
  - qq: 844157922
    mail: root@wsure.top

master:
  - qq: 844157922
    mail: 844157922@qq.com

menu:
  - question: 菜单
    answer: asdaaadd
  - question: help
    answer: adad

#功能命令设置 英文指令名请全小写（禁止大小写混合，否则无法识别）
commands:
  - alia: timestamp
    command: 服务器时间
    componentName: warframe
    type: networkWithoutParam
  - alia: news
    command: 新闻
    componentName: warframe
    type: networkWithoutParam
  - alia: events
    command: 活动
    componentName: warframe
    type: networkWithoutParam
  - alia: alerts
    command: 警报
    componentName: warframe
    type: networkWithoutParam
  - alia: sortie
    command: 突击
    componentName: warframe
    type: networkWithoutParam
  - alia: Ostrons
    command: 地球赏金
    componentName: warframe
    type: networkWithoutParam
  - alia: Solaris
    command: 金星赏金
    componentName: warframe
    type: networkWithoutParam
  - alia: fissures
    command: 裂缝
    componentName: warframe
    type: networkWithoutParam
  - alia: flashSales
    command: 促销商品
    componentName: warframe
    type: networkWithoutParam
  - alia: invasions
    command: 入侵
    componentName: warframe
    type: networkWithoutParam
  - alia: voidTrader
    command: 奸商
    componentName: warframe
    type: networkWithoutParam
  - alia: dailyDeals
    command: 达尔沃
    componentName: warframe
    type: networkWithoutParam
  - alia: persistentEnemies
    command: 小小黑
    componentName: warframe
    type: networkWithoutParam
  - alia: earthCycle
    command: 地球
    componentName: warframe
    type: networkWithoutParam
  - alia: cetusCycle
    command: 平原
    componentName: warframe
    type: networkWithoutParam
  - alia: constructionProgress
    command: 舰队
    componentName: warframe
    type: networkWithoutParam
  - alia: vallisCycle
    command: 山谷
    componentName: warframe
    type: networkWithoutParam
  - alia: nightwave
    command: 电波
    componentName: warframe
    type: networkWithoutParam
  # 灰机wiki
  - alia: wiki
    command: wiki
    componentName: wiki
    type: networkNeedParam
  # RivenMarket
  - alia: rm
    command: rm
    componentName: rm
    type: networkNeedParam
  # WarframeMarket
  - alia: wm
    command: wm
    componentName: wm
    type: networkNeedParam
  # Game
  - alia: beltAndRoadInitiative
    command: 一带一路
    componentName: game
    type: localGameNeedParam
  - alia: lottery
    command: 抽奖
    componentName: game
    type: localGameWithoutParam
  - alia: retract
    command: 撤回
    componentName: game
    type: localGameWithoutParam

# 禁用的模块
disable:
  - beltAndRoadInitiative
  - lottery
  - retract